### ISSUE TITLE
[Issue] Instat restart after Pokemons list loads

### ISSUE THREAD

**Issue by aureliq** [Spegeli/Pokemon-Go-Rocket-API#102]
Instat restart after Pokemons list loads.
Also JsonReader error 

![nb](https://cloud.githubusercontent.com/assets/20686922/17183990/4916adc8-542a-11e6-8532-1a7122b17fae.PNG)

**Comment by netti1337** [comment]
yea new version is broken :(

**Comment by Spegeli** [comment]
This cant be my offical version because i dont use JSON.
So no support from my Side, sorry.
