### ISSUE TITLE
(PKMN) (CatchFlee) | ...

### ISSUE THREAD

**Issue by xclusive707** [Spegeli/Pokemon-Go-Rocket-API#105]
Hi, i still get the message (PKMN) (CatchFlee)...
i  catch maybe 2 of 20 Pokemonm whit the bot, since today (before the update too)
i dont know what to do anymore i tryed to swich the location but it still fails.

**Comment by wesyr** [comment]
probably you got softbanned, search for QuickSpin - PokemonGo Softban Unbanner.

**Comment by xclusive707** [comment]
If i had a softban i couldn't catch any Pokémon or would not get XP for pokestops dude

**Comment by xclusive707** [comment]
![unbenannt-1](https://cloud.githubusercontent.com/assets/20687627/17186485/c8c9a218-5435-11e6-9300-a88ef87b6434.jpg)

**Comment by qdlmcfresh** [comment]
Also noticed this. Many catches fail but some dont.

**Comment by Spegeli** [comment]
This is not a Bot issue. Happens sometimes randomly.
Think that has something to do with the Pokemon Server.

**Comment by xclusive707** [comment]
but if i run another bot with same cordinates at the same time it doesn't hapen on necro or other bots
