### ISSUE TITLE
Can you add UseIncense**? PLZ

### ISSUE THREAD

**Issue by Crankers** [Spegeli/Pokemon-Go-Rocket-API#111]
//Same can be done for
//ITEM_INCENSE_ORDINARY = 401,
//ITEM_INCENSE_SPICY = 402,
//ITEM_INCENSE_COOL = 403,
/ITEM_INCENSE_FLORAL = 404,

//In "Logic.cs" in same spot as LuckyEgg
//1
private static DateTime _lastIncenseTime;

//2
if (_clientSettings.UseIncenseOrdinary)
await UseIncenseOrdinary();

//3
public async Task UseIncenseOrdinary()
 {
var inventory = await _inventory.GetItems();
var IncenseOrdinary = inventory.Where(p => (ItemId)p.Item_ == ItemId.ItemIncenseOrdinary).FirstOrDefault();

if (IncenseOrdinary == null || IncenseOrdinary.Count <= 0 || _lastIncenseTime.AddMinutes(30).Ticks > DateTime.Now.Ticks)
return;

_lastIncenseTime = DateTime.Now;
await _client.UseIncenseItem(ItemId.ItemIncenseOrdinary);
Logger.Write($"Used Ordinary Incense, remaining: {IncenseOrdinary.Count - 1}", LogLevel.Incense);
 }

//In ISetting.cs
//1
bool UseIncenseOrdinary { get; }

//In Setting.cs
//1
public bool UseIncenseOrdinary => UserSettings.Default.UseIncenseOrdinary;

//In UserSettings.settings
//1
UseIncenseOrdinary as bool

//In Client.cs
//1
public async Task<UseItemRequest> UseIncenseItem(ItemId itemId)

{
var customRequest = new UseItemRequest
{
ItemId = itemId,
 };

var useItemRequest = RequestBuilder.GetRequest(_unknownAuth, CurrentLat, CurrentLng, CurrentAltitude,
 new Request.Types.Requests
{
Type = (int)RequestType.USE_INCENSE,
Message = customRequest.ToByteString()
});
return
await
 _httpClient.PostProtoPayload<Request, UseItemRequest>($"https://{_apiUrl}/rpc",
useItemRequest);
}

**Comment by Spegeli** [comment]
are there any infos for:

//ITEM_INCENSE_SPICY = 402,
//ITEM_INCENSE_COOL = 403,
/ITEM_INCENSE_FLORAL = 404,

what is different to the ORDINARY one? only the duration time?

**Comment by Crankers** [comment]
Thankyou!  Next I'm working on PushBullet (Stop ,Start, Hourley Status Updates, and New Type of Registered in Pokedex.
