### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by jtrolfsen** [Spegeli/Pokemon-Go-Rocket-API#115]
so i downloaded all the files that were here, mind you i started with v1.0 this morning, downloaded v2.0 off some website, the console then told me there was a new version available at this link. i download this one, go into the config file(App.config) and edited everything to where i want it(longitude and latitude), and then i started looking around through the files trying to find the console file, normally a .exe . but what i noticed is, there is no .exe in my download. and i tried using both the v1.0 and the v2.0 consoles but it didnt work, i looked through the files here on github and still found no .exe file. could someone please tell me how im supposed to run this if i cant find the .exe file? please help! big fan of v1.0 btw, worked great until level 20 when i started missing every pokemon in console

**Comment by Spegeli** [comment]
Sorry i dont give Support for Forks of my Fork.
I will add tomorrow some infos to my Wiki how to use this uncomplied version.
