### ISSUE TITLE
Crashes after copy'ing refresh token to clipboard - first time setup.

### ISSUE THREAD

**Issue by mickeyunagee** [Spegeli/Pokemon-Go-Rocket-API#117]
> [12:17:51] Google Device Code copied to clipboard
> Unhandled exception: System.ArgumentNullException: En værdi må ikke være null.
> Parameternavn: text
>    ved System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
>    ved System.Windows.Forms.Clipboard.SetText(String text)
>    ved PokemonGo.RocketAPI.Login.GoogleLogin.<>c__DisplayClass6_0.<GetDeviceCode>b__0() i C:\Users\m_000\Desktop\Spegili\PokemonGo.RocketAPI\Login\GoogleLogin.cs:linje 63
>    ved System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    ved System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    ved System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    ved System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    ved System.Threading.ThreadHelper.ThreadStart()
> Press any key to continue . . .

Crashes after copy'ing refresh token to clipboard - first time setup.
The bot still works on on old user with refresh token.

**Comment by Denuth** [comment]
Servers are really unstable right now not sure if that makes a difference,
some of my accounts work some don't. Hope that might help!

**Comment by marcospic** [comment]
I had and existing account and i have the same issue.
I think this appears when a new token is requested from the google api. If you still have the old token it works.

**Comment by infamouslouis** [comment]
I'm having the same problem mickeyunagee :/
