### ISSUE TITLE
not to catch list doesnt work

### ISSUE THREAD

**Issue by snaetch** [Spegeli/Pokemon-Go-Rocket-API#121]
am i missing something or is it just not working? same with spearows
![image](https://cloud.githubusercontent.com/assets/16224965/17210789/4a48c776-54c5-11e6-9f09-6911f63a1ef7.png)
![image](https://cloud.githubusercontent.com/assets/16224965/17210802/62c2a362-54c5-11e6-8f5b-dc3340e75066.png)
![image](https://cloud.githubusercontent.com/assets/16224965/17210812/70111152-54c5-11e6-8ec0-dec99dd76b5d.png)

**Comment by Spegeli** [comment]
hehe your right. seems i missed to add the list check to the catch logic ^^

**Comment by Spegeli** [comment]
Is this UsePokemonToNotCatch or UsePokemonToNot Transfer option in the Settings?
