### ISSUE TITLE
Google Bug ?

### ISSUE THREAD

**Issue by scobinot** [Spegeli/Pokemon-Go-Rocket-API#122]
When I run pokemon mode bot "google" , I can put you over the code that request because it does not appear how to do?

**Comment by XiaoL0609** [comment]
same problem

**Comment by Spegeli** [comment]
it's unbelievable...is it really so hard to look if maybe a Ticket for this issue already exists?

https://github.com/Spegeli/Pokemon-Go-Rocket-API/issues/119
