### ISSUE TITLE
Program Auto Close With Several Error

### ISSUE THREAD

**Issue by hinjuros** [Spegeli/Pokemon-Go-Rocket-API#127]
this noon I encounter problem when starting your application, can you help ?
![image](https://cloud.githubusercontent.com/assets/20703232/17212676/db4bb7bc-54fa-11e6-9252-1d562ee8583a.png)

**Comment by Spegeli** [comment]
it's unbelievable...is it really so hard to look if maybe a Ticket for this issue already exists?

https://github.com/Spegeli/Pokemon-Go-Rocket-API/issues/119
