### ISSUE TITLE
How to run PokemonGoRocketAPI on Linux Environment 

### ISSUE THREAD

**Issue by TRUSTMEIMJEDI** [Spegeli/Pokemon-Go-Rocket-API#128]
How to run PokemonGoRocketAPI on Linux?
I tried with mono its fine but something goes wrong with mscorlib, all dll libraries are complete.
Screen here: 
http://i.imgur.com/Mp9owXP.png

**Comment by Spegeli** [comment]
As i know its not fully functional with unix.
I dont own a UNIX System so i cant fix this, sorry.

**Comment by TRUSTMEIMJEDI** [comment]
okay, thanks for help ;)
