### ISSUE TITLE
Whitelist ignore certain pokemon with 1k+ cp have low IV stats, and transfer.

### ISSUE THREAD

**Issue by trana315** [Spegeli/Pokemon-Go-Rocket-API#13]
This is helpful if you bot in central park, and got tons of Pinsir with 1k+ cp plus poor IV stat, this allows to ignore that and transfer those 1k+ cp with certain IV %.
For example:
Pinsir with 1239 cp have 78 % IV stat will be transfer compare to Pinsir with 1394 cp have 89 % IV stat.

**Comment by Spegeli** [comment]
With the latest release you can set perfection over cp (in the settings).
