### ISSUE TITLE
csv export

### ISSUE THREAD

**Issue by 30er** [Spegeli/Pokemon-Go-Rocket-API#131]
string header = "PokemonID,Name,NickName,CP / MaxCP,IV Perfection in %,Attack 1,Attack 2,HP,Attk,Def,Stamina,Familie Candies,IsInGym,IsFavorite,previewLink";

You are missing one header after "Perfection in %"

**Comment by Spegeli** [comment]
What header should be missing?

**Comment by 30er** [comment]
PokemonID - 111	
Name - Rhyhorn
NickName	 - 
CP / MaxCP - 159/159	
IV Perfection in % - 100
???????? - 0
Attack 1 - MudSlapFast
Attack 2 - Stomp
HP - 50
Attk	- 15
Def	- 15
Stamina - 15
Familie Candies	 - 10
IsInGym - 
IsFavorite	- no
previewLink - https://jackhumbert.github.io/poke-rater/#MTExLDI4LDUsMTU5LDUw

hope that can help?
i guess its some kind of perfection?

**Comment by Spegeli** [comment]
Looks fine on my export file: http://i.epvpimg.com/vKoJe.png

Do you use Excel from Microsoft?

**Comment by 30er** [comment]
oh crap.... get it...
percentage...
"12,12"
u should set it under ""

no im on open office

**Comment by Spegeli** [comment]
This CSV use the Excel format.

**Comment by 30er** [comment]
https://en.wikipedia.org/wiki/Comma-separated_values

basically its correct to put text under ""

1997, "Ford" ,E350
"1997", "Ford" ,"E350"

will have same result ;)

**Comment by Spegeli** [comment]
Open Inventory.cs, replace
````
{perfection}
````
with
````
\"{perfection}\"
````
and let me know if the output is correct for you.

**Comment by 30er** [comment]
i tried it directly in csv
and y its working therefor i told u :) 
and 100 is displayed as 100,00 inside csv ;)
thx 4 help

**Comment by Spegeli** [comment]
As you see on the screen in Exell 100,00 has no decimal numbers.
