### ISSUE TITLE
Code Not Show Up So Cannot Connect A Device

### ISSUE THREAD

**Issue by Ofan31** [Spegeli/Pokemon-Go-Rocket-API#134]
Help Please,
PokemonGo.RocketAPI.Console.exe.config already set as instruction.
The problem is when i click PokemonGo.RocketAPI.Console.exe, cmd windows popout and looks like it works. But when its done and show "google device code copied to clipboard" theres no code show up. 
![spegeli](https://cloud.githubusercontent.com/assets/20704620/17215136/15f732e6-5506-11e6-956b-b7120d5aa7c1.jpg)
Automatically google/device popout and ask for the code. I've put ctrl+v to paste the code but its nothing happen and i stuck here until now
![spegeli2](https://cloud.githubusercontent.com/assets/20704620/17215352/cca2d428-5506-11e6-8b6f-75dbb1913abd.jpg)

anyone can help solve this issues?

regards,
OF

**Comment by executor819** [comment]
use google auth old on folder config... or keep wait update

**Comment by kraizy** [comment]
#119
