### ISSUE TITLE
Unlimited lucky egg and incense

### ISSUE THREAD

**Issue by nabilmoosaje** [Spegeli/Pokemon-Go-Rocket-API#135]
Step 1: Now, when you have used the item(s), leave the Pokémon Go app and launch the Settings app on your Android or iOS device. Head on over to the date & time settings which we will be tinkering with.

Step 2: Both iOS and Android provide an option to set the data and time automatically. Make sure that this is toggled off.

Step 3: Now that the automatic setting of the time and date is disabled, set the time on the device back but not by more than 30 minutes.

What will this do? It will increase the amount of time left that the Incense or Lucky Egg has to run.

Step 5: Head back into the Pokémon Go app and you will see that the time left on the Lucky Egg or Incense is now increased by the number of minutes you rolled back the device’s time in Step 3

source and credit: http://www.redmondpie.com/pokemon-go-trick-get-unlimited-incense-lucky-eggs-heres-how/

**Comment by Spegeli** [comment]
Nope it will not increase the time of duration.
This is only a visual effect.
