### ISSUE TITLE
Pokemon transfer

### ISSUE THREAD

**Issue by Brewfasa** [Spegeli/Pokemon-Go-Rocket-API#26]
It seems that the transfer feature on duplicate pokemons isn't working properly.. 
It keeps spamming the transfer of multiple pokemons up to like 5 times before it finally transfered them, this is taking a lot of time which the boot could have used to do other things

https://i.gyazo.com/85966c94cc2127faf484fef1ea0671e2.png

**Comment by Spegeli** [comment]
Bug is know and will investigate later the day

**Comment by lgndz** [comment]
Same issue - it is happening to multiple bots and no fix seems out yet

**Comment by Spegeli** [comment]
Should be fixed with the current version ^^ it was a issue with the cached inventory ^^
