### ISSUE TITLE
Keep pokemons with higher perfect %

### ISSUE THREAD

**Issue by knightblake1** [Spegeli/Pokemon-Go-Rocket-API#27]
Is there a feature where we can keep Pokemon with higher perfect % instead of cp?

**Comment by fluffymigs** [comment]
yes there is:
[link]https://github.com/Spegeli/Pokemon-Go-Rocket-API/pull/2/commits/2f6eb265d847a624aa17c9ba89865e51c152e60a(url)

**Comment by Spegeli** [comment]
I added it to the latest release ;-)
