### ISSUE TITLE
autorestart with problems

### ISSUE THREAD

**Issue by rafalohaki** [Spegeli/Pokemon-Go-Rocket-API#28]
http://screenshot.sh/m1UwjvCzYfeYo
bot is auto-restarting with this errors every 3-6min

**Comment by rafalohaki** [comment]
bot is autorestarting with this errors every 3-6min

**Comment by Spegeli** [comment]
Should be fixed with the latest release.

**Comment by rafalohaki** [comment]
at this moment 0errors :+1:
