### ISSUE TITLE
Just catching pokemon without taking stops

### ISSUE THREAD

**Issue by chrisoro** [Spegeli/Pokemon-Go-Rocket-API#32]
I guess the title says it all.

Just let the bot walk and don't regard stops at all. Maybe it can still traverse them but no actual usage of the stop functionality.

**Comment by Spegeli** [comment]
currently it use the pokestops as navigation points.
another dev is currently working on a "route" navigation, then we can make a "DisablePokestops" option.

**Comment by chrisoro** [comment]
Well how about still using the pokestops as waypoints but just don't interact with them?

My proposal is aiming at not touching every stop but rather ignore them and just catch pokemons (if near)

Would that be possible?

**Comment by chrisoro** [comment]
I took a look at the code myself (I am a dev myself but just have an android phone right now).

From what I can see in this small amount of time:
Logic.cs #325
var fortSearch = await _client.SearchFort(pokeStop.Id, pokeStop.Latitude, pokeStop.Longitude);

Basically make this optional
