### ISSUE TITLE
[Request] Add # poke candies in console and log if possible

### ISSUE THREAD

**Issue by trana315** [Spegeli/Pokemon-Go-Rocket-API#37]
I think it can be useful.

**Comment by Spegeli** [comment]
what are poke candies? o.O

**Comment by fluffymigs** [comment]
First of all this picc explains everything about poke candy:[Picture]http://www2.pic-upload.de/img/31288024/MD0_kMxT8MApJ2Z4j2K3Ron3s1JsUfEn1z8k1qu5OP0.jpg(url)

In short when u transfer a pokemon u get a candy for the poketype needed to evolve

**Comment by Spegeli** [comment]
ah my fail ^^ the "Bonbons" in german ^^
i will take a look later if /how i can grab these infos.

**Comment by fluffymigs** [comment]
Jap Bonbon in Deutsch. XD Diese funktion würd mich auch interessieren. schaue mal wenn ich aus holland wieder da bin XD

**Comment by Spegeli** [comment]
Added with the next Version ;-)
