### ISSUE TITLE
The bot is ignoring MinIVToKeep

### ISSUE THREAD

**Issue by Brewfasa** [Spegeli/Pokemon-Go-Rocket-API#39]
I had some pokemons above the 85% perfection mark that i put, yet the bot transfered them all..
https://i.gyazo.com/7fc795f55784e5f65707f4d5cf136f65.png

Its not that these were interesting pokemons, but it would be really annoying if you HAD good pokemons that were just randomly transfered..

This happens both with IV as priority as IV NOT as priority.. its just ignores it completely..

**Comment by Spegeli** [comment]
Can you give me a Screenshot of your UserSettings please.

**Comment by Brewfasa** [comment]
These are my current settings:
https://i.gyazo.com/df3f52de91b49937d201f66b594a0ad9.png

I thought it worked like:
Keep highest CP + all pokemons that are above the IV threshhold (which is 85% for me)

**Comment by mbastias** [comment]
Sorry if I'm being intrusive, I came with this issue too. People want to keep their high IV pokemon to evolve them manually and check which comes with better moves. That's why in other versions that setting came over the KeepMinDuplicatePokemon.
