### ISSUE TITLE
Pokeball Settings

### ISSUE THREAD

**Issue by Harath** [Spegeli/Pokemon-Go-Rocket-API#46]
Can you make it so we can configure our own pokeball settings
i'm not sure if it was because it's a low perfect % or what but like

[21:43:02] (PKMN) (CatchFlee) | NidoranFemale Lvl 19 (CP 379/475 | 15.00 % perfect) | Chance: 0.34 | 66m dist | with ITEM_POKE_BALL

i feel like that should at least use greatballs considering i have over 100 of them lol.

so can we have a setting if a pokemon is over like xxx CP it uses greatballs and xxx CP it uses ultra and we select what CP that is?

**Comment by Spegeli** [comment]
You can change them in the Logics.cs via GetBestBall() Logic ^^

**Comment by Harath** [comment]
oh thanks man, i was looking for it in the code and couldn't find it :+1:
