### ISSUE TITLE
[TRANSFER] PLEASE READ !!!

### ISSUE THREAD

**Issue by Spegeli** [Spegeli/Pokemon-Go-Rocket-API#47]
Currently the Transfer Logic is:

Select all Pokemon which are not in Gym or marked as Favorite and CP < MinCP
Then checkse the NotToTransfer List.
then depending if prioritizeIVoverCP enabled or not it will do the descending order by CP or IV
and at the end keep the X amount highest/best you set via KeepMinDuplicatePokemon

It will only transfer 100% when you set the KeepMinDuplicatePokemon to 0. But then its your fail.

KeepMinIVPercentage is currently not implanted/working because he will keep the stupid stuff like pokemons with 10 CP.
Need to search for a better KeepMinIVPercentage handling.

**Comment by k0s4m3** [comment]
Here's a minor suggestion:
When we have prioritizeIVoverCP enabled, the section that shows the current Best when catching or transferring a Pokemon still refers to the CP and does not change based on the settings. It would be awesome if that can reflect our best based on CP or IV based on our settings.

A few questions I have (Sorry if they seem repetitive):

1. Does the best refer to the best Pokemon seen in a bot session? Or the best that we currently have in our Pokemon box?

2. If I have prioritizeIVoverCP enabled, and KeepMinCP set to 500...
Will a newly caught Pokemon with higher IV than our current Pokemon but a CP lower than 500 be transferred? Or will it replace our current Pokemon?

3. Does enabling prioritizeIVoverCP bypass the KeepMinCP heck?

4. I realized that even with my KeepMinCP set to 1500, I am still getting plenty of Pokemon below the 1500. Does the bot attempt to keep one of each Pokemon regardless of CP or IV?

5.  If KeepMinDuplicatePokemon is set to 0, will that mean it will keep 0 duplicates? or 0 of each unique Pokemon resulting in a empty Pokemon box?

**Comment by Spegeli** [comment]
1) It was showing always the best CP Pokemon you currently have. But i changed this in the last Version. When PrioritizeIVOverCP is enabled, it shows now the best Perfection Pokemon.

2) The best you currently have in bag

3) It will always keep all Pokemon above KeepMinCP.
All pokemons below KeepMinCp comes to the list and then if you prioritizeIVoverCP enabled, sort them by IV otherwise by CP and then keep the KeepMinDuplicatePokemon you set.

In your example it will keep all pokemon above 500, and the X bests pokemon based on perfection.
I will improve this in the future.

4) Nope, KeepMinCp is always active

5) It with always keep the KeepMinDuplicatePokemon. So if there is no pokemon from this type, it will always keep KeepMinDuplicatePokemon.

5) Evolve and Transfer will be always done after a pokemon catch.


I hope my answer helps you.

**Comment by k0s4m3** [comment]
Thank you for your response, it cleared up most of my questions.
I want to show you some lines in my log with PrioritizeIVOverCP enabled.

[21:12:35] (TRANSFER) Zubat (CP 203 | 71.86 % perfect) | (Best: 417 CP | 54.31 % perfect)
[21:12:35] (TRANSFER) Zubat (CP 10 | 64.74 % perfect) | (Best: 417 CP | 54.31 % perfect)
[21:12:35] (TRANSFER) Zubat (CP 417 | 54.31 % perfect) | (Best: 417 CP | 54.31 % perfect)
...
...
[21:20:30] (TRANSFER) Rattata (CP 155 | 48.35 % perfect) | (Best: 155 CP | 48.35 % perfect)
[21:20:30] (TRANSFER) Tentacool (CP 127 | 38.92 % perfect) | (Best: 622 CP | 84.01 % perfect)
[21:20:30] (TRANSFER) Fearow (CP 456 | 50.79 % perfect) | (Best: 1076 CP | 88.81 % perfect)
[21:20:30] (TRANSFER) Tauros (CP 508 | 79.19 % perfect) | (Best: 1047 CP | 67.83 % perfect)
[21:20:31] (TRANSFER) Spearow (CP 235 | 45.92 % perfect) | (Best: 412 CP | 82.97 % perfect)

It seems that transfer will indeed transfer Pokemon with lower IV if PrioritizeIVOverCP is enabled.
However, the Best seems to show the best based on CP. 

In the first part, the best for all three Zubats show the third Zubat and the third line shows the Best Zubat being transferred. This probably means that I have another Zubat in my box with higher IV, but is not listed as the best.

In the second part, a Tauros with a higher IV than the listed Best is being transferred. I'm guessing this means that I have a Tauros with a higher IV than the transferred Tauros, but with a CP lower than the listed Best.

Maybe I don't have the latest version.
This is the one I am currently using:

No Version Check + Location Fix + Egg Crash Fix + Origin Fix + Prioritize IV over CP (2016-07-24)
Spegeli (GitHub)
https://mega.nz/#!WJUhBKIJ!0Q54SjuGj...ETrPBWfYv_3OaM

Source:
http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/563350-maclones-community-versions-compiled-ready-go-pokemongo-bots.html

**Comment by TehChozinOne** [comment]
So I assume KeepMinIVpercentage still not working even with the lastest version correct?

**Comment by Spegeli** [comment]
Added new Settings Options with the last Release:

> UsePokemonToNotTransferList
> UseTransferPokemonKeepAboveCP
> TransferPokemonKeepAboveCP
> UseTransferPokemonKeepAboveIV
> TransferPokemonKeepAboveIVPercentage
> 
> Removed UseLuckyEggsWhileEvolving and add a general UseLuckyEggs function
> Removed nearly all Delays (because nobody needs them)
> Added MaxCP to Transfer output
> GPX comma & dot issue which was region based, should be fixed. Use now the default GPX Format with dots, the Bot will auto convert them into commas when needed.
> Lots of small logics fixes
