### ISSUE TITLE
no catch pokemon filter

### ISSUE THREAD

**Issue by harrypoter55** [Spegeli/Pokemon-Go-Rocket-API#50]
**in options of pokemons to not catch,i added rattata and doduo but he keep catching them look :** 
//Type of pokemons not to catch
                var defaultText = new string[] { "Zubat", "Pidgey", "Rattata", "Doduo" };
                _pokemonsNotToCatch = _pokemonsNotToCatch ?? LoadPokemonList("Configs\\ConfigPokemonsNotToCatch.txt", defaultText);
                return _pokemonsNotToCatch;

**+ im asking if there is any option to ignore or disable transfering pokemons according to IV**

**and in game for an exemple i have 2 pokemons same CP, how do i know the one with more IV ?**

**Comment by Spegeli** [comment]
Do you enabled "UsePokemonToNotCatchFilter" via the Settings?
