### ISSUE TITLE
[REQUEST ACCEPTED] Use balls based on IV and Chance

### ISSUE THREAD

**Issue by itzvenom** [Spegeli/Pokemon-Go-Rocket-API#53]
Please, do a better system where the balls are used more accurately, the bot shouldn't be throwing a poke ball for a 100% IV pokemon or a 0.10% chance to caught just because the pokemon is below a certain CP.
CP means nothing in this case.

**Comment by Spegeli** [comment]
I changed some values with the last release.
More adjustems coming in the future.
