### ISSUE TITLE
[Question/Issue] Pokemon attracted by Smoke / Lure

### ISSUE THREAD

**Issue by cmiko-tgm** [Spegeli/Pokemon-Go-Rocket-API#57]
Hello,

Is there a way to implement that Pokemon which are attracted by smoke/lure can be tracked as well as random spawned ones? I tried to get their position with:

var mapObjects = await _client.GetMapObjects();
var pokemons = mapObjects.MapCells.SelectMany(i => i.CatchablePokemons);

But they are not in the list so they can't be encountered.

Any suggestions?

**Comment by davidmann4** [comment]
this feature is not handled by a single API 

good overview about the structure: https://github.com/Grover-c13/PokeGOAPI-Java/issues/125

https://github.com/Grover-c13/PokeGOAPI-Java/issues/167

very hard one - nobody was able to solve it yet!
