### ISSUE TITLE
[ISSUE] Error No Pokestops within 3000m Choose Diferent GPS Location

### ISSUE THREAD

**Issue by namae01** [Spegeli/Pokemon-Go-Rocket-API#61]
Even though there are many many pokestops in the area..

**Comment by Spegeli** [comment]
do you tried a different location? can you test it with another account?
sometimes user geht a 0 pokestop response from the server, but currently i dont know why. this happens very rare.

**Comment by namae01** [comment]
Yes I've tried using a different location, but I got the same result :\

**Comment by Spegeli** [comment]
Can you try it with another account (at the same location) please.

**Comment by namae01** [comment]
Actually..it seems though Im not able to change my location, even though I've edited it..the bot wants to take 73 minutes to get to a different location..
