### ISSUE TITLE
[REQUEST ACCEPTED] UseLuckyEgg needs improved

### ISSUE THREAD

**Issue by Spegeli** [Spegeli/Pokemon-Go-Rocket-API#64]
Only for myself ;-)

I need to add a Buff checker if XPBuff already active.

**Comment by Navyguy330** [comment]
How do you get it to work??  I cannot figure out how to get it to use them, also how often does it use them?

**Comment by Navyguy330** [comment]
maybe just set an await timer for every 31 mins? I mean they only work for 30 mins lol (linked to system time, / log output (if it crashed or was closed etc)

**Comment by Spegeli** [comment]
Currently it will be only used when useLuckyEggsWhileEvolving is enabled via the Settings and the char is doing evolve.
But there is corrently no "Only use Egg when Egg Buff is already active" check, so it maybe makes a error.

**Comment by earshel** [comment]
I also had this problem. The way that I solved it was by checking to see if the xp gained from an evolve was 500 - if true, no egg is active, pop an egg.  This currently seems to be working for me:

` if (evolvePokemonOutProto.ExpAwarded == 500)
                    {
                        await UseLuckyEgg();
                    }
                    else
                    {
                        Logger.Write("Another egg is still active, not activating egg.");

                    }`

**Comment by Navyguy330** [comment]
Ok so I treid to edit that line but is telling me there is no setting for useLuckyEggsWhileEvolving

**Comment by earshel** [comment]
Navyguy, are you on the most recent version? Also, make sure to delete line 452-463 and paste my for loop in its place.

**Comment by Navyguy330** [comment]
Yeah latest version.  Guess it's already enabled.

**Comment by Spegeli** [comment]
Lastest version use now a general UseEgg function: https://github.com/Spegeli/Pokemon-Go-Rocket-API/commit/0a9cb0642de497fdee41fcf22ef1d1149a41d46b
