### ISSUE TITLE
[Request] Transfer Pokemon only if not enough candies for evolving

### ISSUE THREAD

**Issue by Darkztar** [Spegeli/Pokemon-Go-Rocket-API#65]
It would be great if there were an option that only pokemon would be transferred (in all transfer modes) if there aren't enough candies.

E.G. It would transfer that amount of Pidgeys where aren't enough candies for evolving and leave an amount of Pidgeys where all can be evolved according to the candies.

This function is already implemented here:
 https://github.com/imoutits/pokemongo-api

But it would be great to have this function here in the best bot out there :)

Thank you very much.

**Comment by Spegeli** [comment]
1) The bot is doing evoles before Transfer
2) When NotTransferPokemonsThatCanEvolve is enabled, he will not Transfer Pokemons with enough candies for a evolve.

**Comment by Darkztar** [comment]
Yes, sorry, it is working :)

Didn't saw this function.
