### ISSUE TITLE
[REQUEST ACCEPTED] Add more info to CSV and better organize

### ISSUE THREAD

**Issue by qaqsd123** [Spegeli/Pokemon-Go-Rocket-API#68]
https://github.com/NecronomiconCoding/NecroBot/pull/462

I tested it out, and this guys export stats were really organized. Everything was in a different cell, and he even had hyperlinks to "https://jackhumbert.github.io/poke-rater" for each pokemon.

**Comment by Spegeli** [comment]
i already added some more infos to my latest release but will take a look tomorrow of the solution from this guy.

**Comment by Spegeli** [comment]
Already added to the lastes version.
