### ISSUE TITLE
Highest Perfect

### ISSUE THREAD

**Issue by onigumo1990** [Spegeli/Pokemon-Go-Rocket-API#70]
Hello, at the beginning of the program it shows my highest perfect pokemon, I don't know if this is an issue and would like to be enlightened. So I have this line

[22:43:18] (INFO) # CP   71/  75 | (88.95% perfect)     | Lvl 10         NAME: 'Magikarp'

So does that mean it's my Magikarp with 71CP? is 75CP the highest for the best Magikarp? I have one that's also 73CP, is that one not therefore more perfect?

**Comment by Spegeli** [comment]
Nope its normal that on StartUp he prints you the best Pokemons based on CP and IV.

And yeah this means your Magikarp with 71 CP has a 88,95% perfection.
currently i forget for what the 2nd CP value stands *g*

**Comment by onigumo1990** [comment]
Sorry, I guess I worded that weird. The issue I was wondering about was the part about the CP stuff. I don't actually use the program, when I was told it analyzes your Pokemon, that's the reason I use it. I actually currently have a breakpoint in the project so that it stops when I get the info I need.

I will be looking into listing all of my Pokemon's stuff, but I was just curious about this other information.

So what you're saying is that my 71 CP Magikarp is indeed more perfect than my 73 CP Magikarp?

**Comment by Spegeli** [comment]
Compare the % perfection then you know the answer ;-)
