### ISSUE TITLE
Find lured pokemon / use incense (or lure modules on non lured stops?)

### ISSUE THREAD

**Issue by Navyguy330** [Spegeli/Pokemon-Go-Rocket-API#75]
I was wondering if it does this already and if not can it be possible to enable it??

Does the bot look for and catch all pokemon or only ones spanwed etc. ?  does it see any that are spawned from using an incense or oes that spawn at lure modeuled stops?

**Comment by Spegeli** [comment]
Lure Pokemon not available, read more here: https://github.com/Spegeli/Pokemon-Go-Rocket-API/issues/57
