### ISSUE TITLE
CatchFlee more :(

### ISSUE THREAD

**Issue by letuananh035** [Spegeli/Pokemon-Go-Rocket-API#76]
4-5 pokemon CatchFlee after reset bot

**Comment by Navyguy330** [comment]
yeah they really are fleeing quite a bit, I bet the time for catching has shrunk ill check the encounter awaits. anything less than like 3-4 seconds and good luck catching any lol

**Comment by aapikz** [comment]
yea same but i fix it by increasing raspbery usage https://github.com/Spegeli/Pokemon-Go-Rocket-API/issues/60

**Comment by Navyguy330** [comment]
#60?  You mean 60%.  What value ?

**Comment by Navyguy330** [comment]
Oh didn't see the link (was viewing email notice lol)

**Comment by Navyguy330** [comment]
Oh the picture doesn't have any value changes.  what did you change?

**Comment by aapikz** [comment]
edit oops even i increase my razbery value. its no effect as well.. im not softbanned and have enough pokeballs but they're flee/escape 4 out of 5 pokemons :(
![flee](https://cloud.githubusercontent.com/assets/14224262/17097661/90959286-5213-11e6-962d-7b4673258629.png)

**Comment by Navyguy330** [comment]
I think that we need to lower the cost they get used at.  So anything under
100cp uses normal but over is ultra Ball lol

**Comment by Navyguy330** [comment]
That or try multiple times.
