### ISSUE TITLE
[REQUEST ACEPTED] Keep all pokemon with Perfection OR CP set

### ISSUE THREAD

**Issue by can99** [Spegeli/Pokemon-Go-Rocket-API#78]
so my setting
keepMinIVPercentage : 90%
KeepMinCP : 1000
KeepMinDuplicate: 1
Prioritize IV over CP : True

my problem is:
i got 98% and 97% perfection eeveee

i want to keep em both, and they both over the percentage i want
but the bot transfer the 97% instead of keep it coz of minDuplicate is 1 i believe
increasing the minDuplicate will only makes the bot catch useless pokemon
how can i set the bot to not doing this?
the Pokefast 1.0 could do this, but i use yours coz of the item setting
please help

**Comment by Spegeli** [comment]
There is currently no option for doing this.
The only solution is to increase the KeepMinDuplicate value.

I will do more improvements to the Transfer and Evolve function but there are some issue i need to fix first.

**Comment by Spegeli** [comment]
The latest Version now has a Option (inlcuding a Settings Toggle) for this now ^^
