### ISSUE TITLE
Bot randomly closing

### ISSUE THREAD

**Issue by DangersClose** [Spegeli/Pokemon-Go-Rocket-API#80]
Bot randomly closes after about a hour and a bit. I am running 3 different bots all with the same settings and same locations and some of them close and some of them don't. I have checked the logs and there are no error messages.

Confirmed on forums that other people are having the same crash with no error in the logs, seems to be at random times.

**Comment by DangersClose** [comment]
Current Settings

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
            <section name="PokemonGo.RocketAPI.Console.UserSettings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
            <section name="PokemonGo.RocketAPI.Console.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
        </sectionGroup>
    </configSections>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  <userSettings>
    <PokemonGo.RocketAPI.Console.UserSettings>
      <setting name="DefaultAltitude" serializeAs="String">
        <value>10</value>
      </setting>
      <setting name="KeepMinIVPercentage" serializeAs="String">
        <value>90</value>
      </setting>
      <setting name="KeepMinCP" serializeAs="String">
        <value>1500</value>
      </setting>
      <setting name="WalkingSpeedInKilometerPerHour" serializeAs="String">
        <value>100</value>
      </setting>
      <setting name="DefaultLatitude" serializeAs="String">
        <value>34.009163</value>
      </setting>
      <setting name="DefaultLongitude" serializeAs="String">
        <value>-118.497098</value>
      </setting>
      <setting name="EvolveAllPokemonWithEnoughCandy" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="TransferDuplicatePokemon" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="UsePokemonToNotCatchFilter" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="KeepMinDuplicatePokemon" serializeAs="String">
        <value>2</value>
      </setting>
      <setting name="AuthType" serializeAs="String">
        <value>Google</value>
      </setting>
      <setting name="PtcUsername" serializeAs="String">
        <value>username</value>
      </setting>
      <setting name="PtcPassword" serializeAs="String">
        <value>password</value>
      </setting>
      <setting name="PrioritizeIVOverCP" serializeAs="String">
        <value>True</value>
      </setting>
      <setting name="MaxTravelDistanceInMeters" serializeAs="String">
        <value>2000</value>
      </setting>
      <setting name="UseGPXPathing" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="GPXFile" serializeAs="String">
        <value>GPXFile.GPX</value>
      </setting>
      <setting name="useLuckyEggsWhileEvolving" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="NotTransferPokemonsThatCanEvolve" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="EvolveOnlyPokemonAboveIV" serializeAs="String">
        <value>False</value>
      </setting>
      <setting name="EvolveAboveIVValue" serializeAs="String">
        <value>95</value>
      </setting>
    </PokemonGo.RocketAPI.Console.UserSettings>
  </userSettings>
</configuration>`

**Comment by Spegeli** [comment]
See https://github.com/Spegeli/Pokemon-Go-Rocket-API/issues/73
