### ISSUE TITLE
anyway to auto update?

### ISSUE THREAD

**Issue by Navyguy330** [Spegeli/Pokemon-Go-Rocket-API#89]
I hate having to update after only a few small (but needed changes) and having to re do all the configuration for my 3 different accounts. 

anyone know if theres an easier way than DL the zip and basically starting from scratch each time (and copy pasting a lot would suck especially when there are several changes. not to mention several bots.

**Comment by Spegeli** [comment]
Within the next days there is a GUI or extern Settings XML File coming, so updates should be easier.
Also looking into Auto Update function ^^
