### ISSUE TITLE
[Request] Delete LastCoords.txt when longer then XX Minutes Offline

### ISSUE THREAD

**Issue by Spegeli** [Spegeli/Pokemon-Go-Rocket-API#9]
When the Bot was Offline for longer then XX Minutes, then delete the LastCoords.txt File and createa new one, so the Bot is starting on the Coords we set in the Settings.

**Comment by Spegeli** [comment]
This function should be available with the latest version ;-)

**Comment by XiCynx** [comment]
![spegelibot_screen](https://cloud.githubusercontent.com/assets/20632191/17541319/4abcef36-5e8c-11e6-8bce-bd0d593a01c9.png)

Ignore this post, just a placeholder for an image host.

**Comment by XiCynx** [comment]
![spegelibot_statisticbar](https://cloud.githubusercontent.com/assets/20632191/17541376/bcfdfad6-5e8c-11e6-9340-003f44653def.png)

Also ignore this post as well, also an image placeholder.
