### ISSUE TITLE
Logging in via Ptc Exception Thrown

### ISSUE THREAD

**Issue by MetalzSlug** [Spegeli/Pokemon-Go-Rocket-API#95]
Getting an "Exception of type 'PokemonGo.RocketAPI.Exceptions.PtcOfflineException' was thrown. from Pokemon Go Rocket API."
Settings are correct, Possible Ptc down?
![window](https://cloud.githubusercontent.com/assets/20684453/17178696/5ace37e6-540e-11e6-8276-952c48cc15fb.png)
Anti virus and firewall are off

**Comment by trana315** [comment]
you didn't verify your email, or ptc server probably down now, too https://go.jooas.com/

**Comment by OZone998** [comment]
All PTC Login Servers are down: http://ispokemongodownornot.com/
We just have to wait.

**Comment by Spegeli** [comment]
Will add a better Exceoption output in the near future ^^
