### ISSUE TITLE
[ISSUE] Cant claim pokestop iteams

### ISSUE THREAD

**Issue by snaetch** [Spegeli/Pokemon-Go-Rocket-API#96]
hey guys, i dont know why but it certainly wont claim any iteams from the pokestop so i ran out of it very fast. i thought it might be the speed which is too high but also with a lower speed it doesnt work. any ideas?
thanks

![image](https://cloud.githubusercontent.com/assets/16224965/17179785/ae052580-541a-11e6-84dd-fef55814fb4e.png)

**Comment by Spegeli** [comment]
maybe soft-banned?

**Comment by snaetch** [comment]
i set speed to 60 but reduced it to 20 and 10 for checking.. is there a page i can check for the softban?

**Comment by Spegeli** [comment]
Nope. To dou have a 2nd Account for Testing?
Do you have pokeballs in the inventory?

**Comment by snaetch** [comment]
i dont have any in the inventory but i had the same idea with the second account just before you wrote it, im bout to check

**Comment by snaetch** [comment]
okay it seems to work with the second account.. looks like it indeed had been a ban mh.. thanks anyway spegeli
