### ISSUE TITLE
[Question] Where to change the lists(NotToTransfer, NotToEvolve etc)? 

### ISSUE THREAD

**Issue by DuilioFrancis** [Spegeli/Pokemon-Go-Rocket-API#99]
I can't see the document in /bin/debug/config to edit the list of what I want to transfer etc. I need to edit in Visual Studio? '-'

**Comment by wesyr** [comment]
Try .../PokemonGo.RocketAPI.Console\bin\Debug\Settings :)

**Comment by XiCynx** [comment]
^^What he said, I was just about to post that.

**Comment by DuilioFrancis** [comment]
@wesyr but there's nothing in "debug" folder.

**Comment by DuilioFrancis** [comment]
Look:
![311](https://cloud.githubusercontent.com/assets/20686500/17183754/5965abfa-53ff-11e6-9d5a-02eb049e941c.png)

**Comment by wesyr** [comment]
Did you run the new version ? It must create those files first :)

**Comment by XiCynx** [comment]
Yes, you must run the bot at least once in order for it to create all the necessary files within those folders.
